title: TL的个人页面
page-top-title: Tianle Yin
top-section-bg-text: Control Science and Engineering
home-subtitle: Tianle Yin&ensp;|&ensp;尹天乐
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
